Repository 24-1-LikePotato/Zipbap-Coin-FE, pull requests merged in 2024-07, with the labels that each got.

#11 feat/login page
  public/assets/fonts/GongGothicOTF.otf
  public/assets/icons/bowl-rice.png
  public/assets/images/kakao_login_btn.png
  src/components/fonts/GongGothicFontStyle.jsx
  src/pages/LoginMain.jsx
Labels: feat

#13 Feat/NavBar
  src/components/Button/StyledIcon.jsx
  src/components/header/NavBar.jsx
  src/index.js
Labels: feat

#14 Feat/name header
  public/assets/fonts/GongGothicOTF.otf
  src/App.js
  src/components/header/NameHeader.jsx
  src/index.js
  src/pages/Ingredients.jsx
  src/pages/LoginMain.jsx
Labels: feat, fix

#15 Feat/ingredients
  src/components/container/WhiteWrapContainer.jsx
  src/components/header/NameHeader.jsx
  src/pages/Ingredients.jsx
Labels: feat, style

#16 Fix/login button icon quality, WhiteWrapContainer margin
  public/assets/icons/bowl-rice.png
  public/assets/images/kakao_login_btn.png
  src/components/container/WhiteWrapContainer.jsx
  src/pages/LoginMain.jsx
Labels: fix

#18 fix:WhiteWrapContainer children prop added
  src/components/container/WhiteWrapContainer.jsx
Labels: fix

#20 Feat/ingredients
  src/components/Button/DetailButton.jsx
  src/components/Button/StandardButton.jsx
  src/components/container/HorizontalScrollContainer.jsx
  src/components/container/ImageContainer.jsx
  src/components/container/WhiteWrapContainer.jsx
  src/components/header/NavBar.jsx
  src/pages/Ingredients.jsx
Labels: feat, fix, design

#21 feat/home
  public/assets/icons/decrease.png
  public/assets/icons/increase.png
  src/components/Home/Recommend.jsx
  src/components/Home/TodayFood.jsx
  src/components/Home/TodayPrice.jsx
  src/components/Input/Search.jsx
  src/pages/Home.jsx
Labels: feat

#22 Feat/ingredients
  package.json
  src/components/Button/StandardButton.jsx
  src/components/Ingredients/IngredientInfo.jsx
  src/components/Ingredients/RelatedIngredients.jsx
  src/components/container/GraphContainer.jsx
  src/components/container/TitleTextContainer.jsx
  src/pages/Ingredients.jsx
  yarn.lock
Labels: feat, refactor

#24 fix:Home_TodayFood-HorizonScroll
  src/components/Home/TodayFood.jsx
Labels: fix

#28 Feat/ingredients,refrigerator
  src/components/Button/StandardButton.jsx
  src/components/Ingredients/IngredientInfo.jsx
  src/components/Ingredients/RelatedIngredients.jsx
  src/components/Refrigerator/IngredientDateRemain.jsx
  src/components/Refrigerator/MyRefrigerator.jsx
  src/components/Refrigerator/RefrigeratorGrid.jsx
  src/components/Refrigerator/RefrigeratorModalOverlay.jsx
  src/components/Refrigerator/SubscribeIngredients.jsx
  src/components/container/WhiteWrapContainer.jsx
  src/pages/Ingredients.jsx
  src/pages/Refrigerator.jsx
Labels: feat, fix, design

#29 chore: install typewriter_effect
  yarn.lock
Labels: chore

#32 Feat/minor additions and fixes
  src/App.css
  src/components/Ingredients/GraphDataEmpty.jsx
  src/components/Ingredients/IngredientInfo.jsx
  src/components/Refrigerator/DeleteConfirmationModal.jsx
  src/components/Refrigerator/IngredientDateRemain.jsx
  src/components/Refrigerator/RefrigeratorGrid.jsx
  src/components/Refrigerator/RefrigeratorModalOverlay.jsx
  src/components/container/GraphContainer.jsx
  src/components/header/NavBar.jsx
  src/pages/LoginMain.jsx
Labels: feat, fix, design

#33 fix: resolve title bold issue on iPhone in LoginMain
  public/assets/fonts/GongGothicBoldOTF.otf
  src/components/fonts/GongGothicBoldFontStyle.jsx
  src/pages/LoginMain.jsx
Labels: fix, design
